### ISSUE TITLE
Update 'Data Management' guidelines article URL in training docs, or include the PDF directly

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/datateam-training#10]
The URL we currently list in "01_Introduction.Rmd" for "effective data management" does not resolve any longer, but this one does (for now):

http://www.jstor.org/stable/pdf/bullecosociamer.90.2.205.pdf?refreqid=excelsior:086f3755ac689fab9f491f083875cb0c

Consider downloading the PDF and storing it in our repo.

**Comment by jagoldstein** [comment]
https://drive.google.com/drive/u/0/folders/0BzPRanIZGBMARldSblh1Vm9ZcEk

added the PDF to ADC G Drive ^

**Comment by isteves** [comment]
Added pdf's to repo and edited links within the intro rmd
