### ISSUE TITLE
Data Team Training Issues

### ISSUE THREAD

**Issue by CSemnacher** [NCEAS/datateam-training#104]
- Broken link in 1.2 Effective Data Management to Matt Jones et al.’s paper on effective data management
- 404 Webpage not found for eml-party (2x) and eml-attribute, and eml-physical under 3.2 "Understand the EML schema"
- Link not found for "exploring EML (more on that **here**)" under 3.3 "Access specific elements"
- 404 Webpage not found for "attributeList" under 4.3 "Edit attributeLists"
- 5.7.1 - Blank link - Under provided dataset "Nothing was found"

**Comment by dmullen17** [comment]
You can also add you need to talk to Nick in #computing on Slack to get your LDAP account activated for GH enterprise once it's set up
