### ISSUE TITLE
Custom units example

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datateam-training#109]
I noticed that we don't have an example of creating a custom units data frame in section 4.3.2 of [Editing EML](https://nceas.github.io/datateam-training/training/editing-eml.html).  Additionally some of the references to the `datamgmt` functions in that section are now deprecated.  

- [ ] Create an example `custom_units` data frame with 3ish custom units 
- [ ] Remove any deprecated `datamgmt` functions and replace those workflows with appropriate instructions

**Comment by dmullen17** [comment]
@rachelsun97

**Comment by dmullen17** [comment]
@rachelsun97 could you take this one?

**Comment by rachelsun97** [comment]
@dmullen17 Yep I can take this one!
