### ISSUE TITLE
Add recover_failed_submission to reference guide 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datateam-training#111]
We should add a short section here about using the `recover_failed_submission` function.  It should include details about what happens when a submission fails - metacatUI catches a submission error and uploads the EML text as a data object instead.  Next, we can use the `recover_failed_submission` function to try to remove the error text and get a valid EML document - note that this may not always work based on the error.  Finally we want to upload the recovered document as a metadata document and set the rights and access to the correct submitter.

**Comment by rachelsun97** [comment]
@dmullen17 I can work on this!
