### ISSUE TITLE
Broken Link - Simple Data Management Paper

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/datateam-training#114]
In 1,2 (Effective Data Management), there's a broken link. 

> Read Matt Jones et al.’s paper on [effective data management] to learn how we will be organizing datasets prior to archival.

I imagine the updated link should be here: https://esajournals.onlinelibrary.wiley.com/doi/epdf/10.1890/0012-9623-90.2.205

**Comment by jeanetteclark** [comment]
resolved in Maya's PR
