### ISSUE TITLE
Text doesn't match what's happening

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/datateam-training#115]
In 3.2, it says:

For example, let’s take a look at eml-party. To start off, notice that some elements are in solid boxes, whereas others are in dashed boxes.

Elements are not in solid/dashed boxes...in fact, the EML-party schema looks nothing like the screenshots on the training page.

**Comment by jeanetteclark** [comment]
Oh yeah, good call. the schema docs all changed when the latest version of EML was released. the screenshots all need to be updated

**Comment by jeanetteclark** [comment]
Maya's PR resolved this I believe
