### ISSUE TITLE
2 broken links in 1st paragraph of datateam-training/workflows/explore_eml/understand_eml_schema.Rmd

### ISSUE THREAD

**Issue by MayaSamet** [NCEAS/datateam-training#117]
Both links in this portion of the paragraph are broken - 

`Additional information on the schema and how different elements (or "slots") are defined can be found [here](https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/index.html)). Further explanations of the symbology can be found [here](https://manual.altova.com/xmlspy/spyenterprise/index.html?xseditingviews_schv_cmview_objects.htm).`

@jeanetteclark I poked around a little but wasn't sure if I was truly finding webpages that would be appropriate replacements, I think you might be a better judge of that / be able to think of some off the top of your head

**Comment by jeanetteclark** [comment]
@MayaSamet I'm not sure what the first link used to point to :/ but all of the new schema docs are here: https://eml.ecoinformatics.org/schema/

**Comment by jeanetteclark** [comment]
resolved in Maya's PR
