### ISSUE TITLE
4.3 remove print button directions ?

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/datateam-training#122]
In my version of the `shiny_attributes` app there doesn't seem to be the print button mentioned. Only a `Download`, `Quit App` and `Help` buttons. Is the workflow different now?

> Once you are done editing a table in the app, click the **Print button** to print text of a code that will build a data.frame in R. Copy that code and assign it to a variable in your script (e.g. attributes - data.frame(...)).

![Screen Shot Shiny App](https://user-images.githubusercontent.com/13112379/78388793-782d4b80-7596-11ea-9aba-87d7275bc5e5.png)

**Comment by jeanetteclark** [comment]
yeah sounds like that description is from a previous version of the function, good catch
