### ISSUE TITLE
adding unitlist to additional metadata

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/datateam-training#133]
I was trying to add custom units based on the editing EML training

I was couldn't run the line (appears to be coercing the unitlist to additionalMetadata):
`doc$additionalMetadata <- c(as(unitlist, "additionalMetadata"))`

The Error seems to be `as(unitlist, "additionalMetadata")`:
```
Error in as(unitlist, "additionalMetadata") : 
  no method or default for coercing “list” to “additionalMetadata”
```

is it ok to go ahead and `doc$additionalMetadata <- unitlist` instead?

**Comment by jeanetteclark** [comment]
I believe @rachelsun97 has a PR in for this for which I've requested a couple of other changes
