### ISSUE TITLE
EML 2.2.0 updates

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/datateam-training#139]
Keeping track on what needs to be updated when we switch to EML 2.2.0
- [x] update `final_review_checklist`
- [x] update `publish_an_object`
- [ ] add section on citations

**Comment by laijasmine** [comment]
new updates: https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html

- [ ] update eml_nsf_to_project()
- [ ] add a citation function?

**Comment by laijasmine** [comment]
-  [ ] add annotation instructions (for the team to add in the back end with all new datasets)

**Comment by jeanetteclark** [comment]
https://eml.ecoinformatics.org/semantic-annotation-primer.html
