### ISSUE TITLE
qa_package() error message

### ISSUE THREAD

**Issue by samanthacsik** [NCEAS/datateam-training#193]
You receive the following error message when running qa_package():

"The distribution URL for object urn:uuid:c04c42ec-f85c-46c2-957c-a81fdb6fe308 is missing or incongruent in the physical section of the EML.
Error in dl_and_read_all_data(mn, package, doc, read_all_data) : 
All distribution URLs for data objects must match the data PIDs to continue."

This is particularly confusing when it happens for the first time in Exercise 3b in Data Team Training -- adding an alert/note to this section as a heads-up for trainees or fixing the qa_package() is recommnended.

**Comment by KellyWang1126** [comment]
@laijasmine Do we just add an alert for the error message for now and then leave the bug to be fixed in the future or we prefer to fix this bug directly? I can add the alert but I don't know how to fix the bug...

**Comment by laijasmine** [comment]
yeah for now we can make a note when we introduce the `qa_package()` that this message will show up and to continue on
