### ISSUE TITLE
add EML paper to training

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/datateam-training#2]
http://onlinelibrary.wiley.com/doi/10.1890/0012-9623(2005)86%5B158:MTVOED%5D2.0.CO;2/abstract

needs to be added to the intro to EML section

**Comment by jagoldstein** [comment]
full article URL:
http://onlinelibrary.wiley.com/doi/10.1890/0012-9623(2005)86%5B158:MTVOED%5D2.0.CO;2/epdf

**Comment by jagoldstein** [comment]
This URL no longer works! Today is the first time I've experienced this. I confirmed with UCSB students and reference library staff.

Here is a different URL that is currently more functional for me:

http://www.jstor.org/stable/pdf/bullecosociamer.90.2.205.pdf?refreqid=excelsior:086f3755ac689fab9f491f083875cb0c

@isteves please update the link in the training doc

Or, longer-term solution: can we download the PDF and store it in our repo without violating any copyrights? Matt and Mark would surely approve.

**Comment by isteves** [comment]
I'm seeing two different articles:

- Maximizing the Value of Ecological Data with Structured Metadata: An Introduction to Ecological Metadata Language (EML) and Principles for Metadata Creation
- Some Simple Guidelines for Effective Data Management

This link works for the Maximizing the Value... article
http://www.jstor.org/stable/pdf/bullecosociamer.86.3.158.pdf?refreqid=excelsior%3Ae800b54bb67b90d78e841e6b4420df5d

I don't know about copyright issues, but perhaps we could store a copy on Google Drive?  or on Enterprise?

**Comment by jagoldstein** [comment]
Ah, I commented in the wrong issue, but similar idea. I should have paid attention to the "EML" part of the title here.

**Comment by isteves** [comment]
Added pdf to repo; linked directly to it in training
