### ISSUE TITLE
Clarify inclusion of "temp" as a requirement for title in initial review checklist

### ISSUE THREAD

**Issue by cwbeltz** [NCEAS/datateam-training#202]
At end of first bullet point after "WHAT, WHERE, and WHEN", we are asked to include "temp".

<img width="821" alt="Screen Shot 2020-08-13 at 1 54 03 PM" src="https://user-images.githubusercontent.com/32374186/90170320-e1f00a00-dd6d-11ea-9b5d-d3d2cd5d170f.png">

**Comment by jeanetteclark** [comment]
I think that is supposed to say "temporal coverage"

**Comment by cwbeltz** [comment]
Ok! Thanks Jeanette. I'll make the edit and submit a PR later today before I finish.
