### ISSUE TITLE
Add graphic for dataset submission workflow

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/datateam-training#203]
create some graphic like the following from the DataOne Community Meeting (Session 7) to help illustrate the dataset submission workflow

<img width="959" alt="Screen Shot 2020-08-13 at 9 15 56 AM" src="https://user-images.githubusercontent.com/13112379/90174649-2cb45680-dd5b-11ea-91ff-486b1b96e346.png">

**Comment by jeanetteclark** [comment]
<img width="1210" alt="packaging" src="https://user-images.githubusercontent.com/24237074/90175740-b7498580-dd5c-11ea-97c9-b5f3d245522a.png">
 
Another one I liked

**Comment by mbjones** [comment]
Agreed, those were great.

Quick note, the `aggregatedBy` arrows are backwards on the second figure.

**Comment by KellyWang1126** [comment]
@jeanetteclark Do you still remember where the workflow image you post here came from? I want to add the original creator for it.

**Comment by laijasmine** [comment]
@KellyWang1126 it was also from the same slide deck in the Dataone community meeting

**Comment by KellyWang1126** [comment]
ah thanks Jasmine!
