### ISSUE TITLE
Suggestion for Training 9.5.3.2 DOI and data package finalization comments

### ISSUE THREAD

**Issue by eeerika** [NCEAS/datateam-training#225]
For this part:
> Here is the link to your finalized data package:

https://doi.org/10.18739/A20X0X

Please let us know if you need any further assistance. However, any further changes to the dataset will result in a new DOI. If you would like to maintain the same DOI please let us know.

--- 
Just a suggestion, but doesn't have to be implemented: I feel like it could be valuable to briefly explain that getting a new DOI doesn't mean the old DOIs wouldn't "work" anymore: there would be a link to the updated version of the dataset at the top of the webpage of the old DOI. It seems like correspondents tend to ask this fairly often so it could be better to briefly explain before they ask, but I also understand that it could also be good to keep it how it is and just give a more detailed explanation if they do ask!

**Comment by laijasmine** [comment]
yeah that would be a good addition!
