### ISSUE TITLE
missing/broken link in 1.1 submission

### ISSUE THREAD

**Issue by melanieleung** [NCEAS/datateam-training#226]
For chapter 1.1 under the topic for submission, which can be found [here](https://arcticdata.io/submit/#introduction), has a sub topic "submission tools" leading to a missing [link](http://training.arcticdata.io/materials/arctic-data-center-training/data-documentation-and-publishing.html#publishing-data-from-the-web) where it says Section 5.7 , "Publishing Data from the Web"

**Comment by laijasmine** [comment]
Updated! Thanks for catching that :)
