### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by csjx** [NCEAS/datateam-training#254]
From an inclusivity perspective, I suggest we rename the `master` branch to `main` and generally use more welcoming terms as we describe our software architectures. The use of the the terms `master` and `slave` in computing are not welcoming.  For context, see the [Inclusive Naming](https://inclusivenaming.org) project and [this repo](https://github.com/github/renaming).

**Comment by laijasmine** [comment]
closing this because this is also mentioned in #223
