### ISSUE TITLE
Add checklist for dataset updates

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/datateam-training#268]
Items to consider when processing datasets that have been recently updated:
- Did the dates change / new data was added? -> `Temporal Coverage` and `Title`
- New files were added -> usual protocols
- Files were replaced -> update physical and entityName
- Is the dataset published before 2021? -> update project info , annotations

**Comment by eeerika** [comment]
Other things that could be good to look into:
- Files were replaced -> double-check attributes are the same, check for any new missing value codes that should be accounted for
- Glance over entire page for any small mistakes (ie. repeated additionalMetadata, any missed &amps, typos)
