### ISSUE TITLE
Solr training issues

### ISSUE THREAD

**Issue by smfreund** [NCEAS/datateam-training#49]
(1) Add tip for using "obsoletedBy" field to find only the most recent versions of the packages you're searching for.
(2) Add an example of a query that looks for packages where fields are missing (e.g. -keywords:*)
(3) The link highlighted at the bottom of the page in this image is broken. 
![image](https://user-images.githubusercontent.com/35786348/40250470-3dc74356-5a8b-11e8-99c3-87eae09c19bd.png)

**Comment by jagoldstein** [comment]
@smfreund thanks for noticing the broken link and for providing these other suggestions.

I will update when I finally get to editing this chapter
