### ISSUE TITLE
explain `cn` and `mn` differences more clearly

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/datateam-training#55]
Section 3.4 I think could benefit from a more robust description of what the different nodes are. This is the question I got about this section:

```On step 3.4, do we set the PROD nodes before setting the Staging nodes? The staging nodes uses cn, which is in the PROD node. When I set the Staging node in the console I get an error saying object: cn is not found. (I dont want to set something up on accident and end up submitting the training set using the PROD node).```

and the answer:
```PROD and STAGING are two different coordinating nodes (`cn`)
and each of those coordinating nodes has many member nodes (`mn`) including KNB and Arctic which have different names depending on which coordinating node you are working in```

**Comment by jagoldstein** [comment]
https://nceas.github.io/datateam-training/training/create-data-packages-in-r.html#set-dataone-nodes

**Comment by jeanetteclark** [comment]
I updated this - but my new picture isn't displaying on the website even though it built correcly :/
